---
# handlers file for bootstrap

- name: restart systemd-logind
  service:
    name: systemd-logind
    state: restarted
  when: ansible_service_mgr == 'systemd'

- name: restart sshd
  service:
    name: "{{ 'ssh' if ansible_os_family == 'Debian' else 'sshd' }}"
    state: restarted

- name: update-grub
  ansible.builtin.command: update-grub
  when: grub_modified.changed  # Only run if a change was made

- name: Remount filesystems if needed
  mount:
    name: /
    state: remounted
  when: fstab_modified is changed
