---
dependency:
  name: galaxy
lint: |
  yamllint .
  ansible-lint
driver:
  name: molecule-qemu
platforms:
  - name: "${MOLECULE_DISTRO:-ubuntu2204}"
    image_url: "${MOLECULE_IMAGE_URL}"
    image_checksum: "${MOLECULE_IMAGE_CHECKSUM}"
    network_ssh_port: 2223
    vm_cpus: 4 # optional, default is 1
    vm_memory: 2048 # optional, default is 512
    vm_disk: 20G # optional, default is 8G
    groups:
      - "${MOLECULE_GROUP:-debian_family}"
    cloud_config:
      user_data: |
        #cloud-config
        packages:
          - python3
          - python3-pip
        package_update: true
        runcmd:
          - [ sh, -c, "alternatives --install /usr/bin/python python /usr/bin/python3 1 || ln -sf /usr/bin/python3 /usr/bin/python || true" ]
provisioner:
  name: ansible
  env:
    ANSIBLE_FORCE_COLOR: "${MOLECULE_ANSIBLE_COLOR:-true}"
  options:
    vvv: "${MOLECULE_VERBOSE:-false}"
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
