---
- name: Prepare
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Wait for system to become reachable
      wait_for_connection:
        timeout: 300

    - name: Gather facts
      setup:

    - name: Update package cache (Debian-based)
      apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

    - name: Install Python for Ansible (if needed)
      raw: |
        if command -v python3 > /dev/null 2>&1; then
          echo "Python3 already installed"
        else
          if command -v apt-get > /dev/null 2>&1; then
            apt-get update && apt-get install -y python3
          elif command -v dnf > /dev/null 2>&1; then
            dnf install -y python3
          elif command -v yum > /dev/null 2>&1; then
            yum install -y python3 
          fi
        fi
      changed_when: false
