---
- name: Prepare
  hosts: all
  become: true
  gather_facts: false
  vars:
    ansible_python_interpreter: auto_silent
  tasks:
    - name: Wait for system to become reachable
      wait_for_connection:
        timeout: 300

    - name: Install Python3 (RHEL/Rocky/AlmaLinux)
      raw: |
        if command -v dnf > /dev/null 2>&1; then
          dnf install -y python3 python3-pip
        elif command -v yum > /dev/null 2>&1; then
          yum install -y python3 python3-pip
        fi
        # Create python symlink if it doesn't exist
        if [ ! -f /usr/bin/python ] && [ -f /usr/bin/python3 ]; then
          alternatives --install /usr/bin/python python /usr/bin/python3 1 || ln -sf /usr/bin/python3 /usr/bin/python
        fi
      when: ansible_os_family is undefined or ansible_os_family == 'RedHat'
      changed_when: false

    - name: Install Python3 (Debian/Ubuntu)
      raw: |
        if command -v apt-get > /dev/null 2>&1; then
          apt-get update && apt-get install -y python3 python3-pip
        fi
      when: ansible_os_family is undefined or ansible_os_family == 'Debian'
      changed_when: false

    - name: Gather facts
      setup:

    - name: Update package cache (Debian-based)
      apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

    - name: Ensure sudo is installed
      package:
        name: sudo
        state: present

    - name: Ensure Python3 is installed via package manager
      package:
        name:
          - python3
          - python3-pip
        state: present